version: '3'
services:
  redis_16379:
    image: redis:my-redis-1.0
    ports:
      - 16379:6379
    # networks: 
    #   default:
    #     ipv4_address: 172.21.0.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  redis_26379:
    depends_on:
      - redis_16379
    image: redis:my-redis-1.0
    ports:
      - 26379:6379
    # networks: 
    #   default:
    #     ipv4_address: 172.21.0.3
    command: ["redis-server", "/usr/local/etc/redis/redis2.conf"]
  redis_36379:
    depends_on:
      - redis_16379
    image: redis:my-redis-1.0
    ports:
      - 36379:6379
    # networks: 
    #   default:
    #     ipv4_address: 172.21.0.4
    command: ["redis-server", "/usr/local/etc/redis/redis3.conf"]
  sentinel_16380:
    depends_on:
      - redis_16379
      - redis_26379
      - redis_36379
    image: redis:my-redis-1.0
    ports:
      - 16380:26379
    # networks: 
    #   default:
    #     ipv4_address: 172.21.0.5
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
  sentinel_26380:
    depends_on:
      - redis_16379
      - redis_26379
      - redis_36379
    image: redis:my-redis-1.0
    ports:
      - 26380:26379
    # networks: 
    #   default:
    #     ipv4_address: 172.21.0.6
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
  sentinel_36380:
    depends_on:
      - redis_16379
      - redis_26379
      - redis_36379
    image: redis:my-redis-1.0
    ports:
      - 36380:26379
    # networks: 
    #   default:
    #     ipv4_address: 172.21.0.7
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]

# networks:
#   default:
#       driver: bridge
#       ipam:
#         config:
#           - subnet: 172.21.0.0/16
